---
title: "コロナ渦での生活保護・住居確保給付金・生活福祉資金"
author: "安藤道人（立教大学経済学部）作成"
date: "`r Sys.Date()`"
output:
 html_document:
    css : R_style.css
    # theme: cosmo
    highlight: haddock     # Rスクリプトのハイライト形式
    code_folding: 'hide'  # Rコードの折りたたみ表示を設定
    toc: TRUE
    toc_depth: 3           # 見出しの表示とその深さを指定
    toc_float: true        # 見出しを横に表示し続ける
    number_sections: true # 見出しごとに番号を振る
    df_print: paged        # head()の出力をnotebook的なものに（tibbleと相性良い）
    latex_engine: xelatex  # zxjatypeパッケージを使用するために変更
    # fig_height: 4.5          # 画像サイズのデフォルトを設定
    # fig_width: 8           # 画像サイズのデフォルトを設定
    dev: png
classoption: xelatex,ja=standard
editor_options: 
  chunk_output_type: console
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

このサイトは、安藤道人・大西連[コロナ渦で生活困窮者への家賃補助と現金貸付が急増：独自入手した厚生労働省データを用いた検証](https://note.com/ohnishiren/n/n7c0773c4f861)に掲載しているグラフを、インタラクティブなグラフとして掲載している。各グラフの説明については、この記事を参照されたい。


また、元データやRMarkdownファイルは[GitHub](https://github.com/michihito-ando/covid19-japan-policies)の「household_support_monthly」のフォルダで公開しているほか、本サイトでもコードは確認できるようにしている。

```{r, include=FALSE}
rm(list = ls())

# pathの設定（Rstudioで実行する場合）

path <- "/Users/Michi/Dropbox/GitHub/covid19-japan-policies/household_support_monthly/R"

setwd(path)

#Font setting

## For Mac
font <- "HiraKakuPro-W3"
## NOte: Package "pacthwork" does not work well with Mac 

## For Windows, 
#extrafont::font_import() 
##Import font if you have not done it
#extrafont::loadfonts(device = "win")
#font <- "Arial"

# packages
library(tidyverse)
library(plotly)
library(readxl)
library(scales)
library(patchwork)
library(extrafont)
```


```{r, warning=FALSE, include=FALSE}
#Read data#

##コロナ前後の住居確保給付金##

# データの読み込み：2019.01-2019.03
jukyo_1901_1903 <- read_excel("jukyo_1901_1903.xlsx")
##"※支給済額は、過去月に決定し支給した額を含む。
## ※2019年度 (2019年4月から2020年3月)については未集計のため、2019年1月から3月までの件数等となります。"

# 2データの読み込み：2020.04-2020.06
jukyo_2004_2006 <- read_excel("jukyo_2004_2006.xlsx")

## "※支給済額は、過去月に決定し支給した額を含む。
## ※本集計は速報値としてとりまとめたものであり、件数、金額に変動が生じることがある。"

# データのバインド
jukyo1901_2006 <- dplyr::bind_rows(jukyo_1901_1903, jukyo_2004_2006)

# 時系列データに変換 
jukyo1901_2006 <-jukyo1901_2006 %>% 
  dplyr::mutate(date = paste(jukyo1901_2006$年, jukyo1901_2006$月, "1", sep = "-"))

jukyo1901_2006$date <- as.Date(jukyo1901_2006$date)

# 変数名の英語化 
jukyo1901_2006 <- jukyo1901_2006 %>% rename(prefec = "都道府県", jukyo_apply = "申請件数", jukyo_number = "決定件数", jukyo_payment_amount = "支給済額(単位：千円）")

# 月・年データの削除
jukyo1901_2006 <- jukyo1901_2006 %>% select(-月, -年)


##コロナ前の緊急小口資金##

# データの読み込み:2019.01-2020.01
koguchi_1901_2001 <- read_excel("koguchi_1901_2001.xlsx")

# 時系列データに変換
koguchi_1901_2001 <- koguchi_1901_2001 %>% dplyr::mutate(date = paste(koguchi_1901_2001$年, koguchi_1901_2001$月, "1", sep = "-"))
koguchi_1901_2001$date <- as.Date(koguchi_1901_2001$date)

# 変数名の英語化
koguchi_1901_2001 <- koguchi_1901_2001 %>% rename(prefec = "都道府県",  koguchi_number = "決定件数",  koguchi_payment_amount = "決定金額")

# 月・年データの削除
koguchi_1901_2001 <- koguchi_1901_2001 %>% select(-月, -年)

##コロナ前の総合支援資金##

# データの読み込み:2019.01-2020.01
sogo_1901_2001 <- read_excel("sogo_1901_2001.xlsx")

# 時系列データに変換
sogo_1901_2001 <- sogo_1901_2001 %>% dplyr::mutate(date = paste(sogo_1901_2001$年, sogo_1901_2001$月, "1", sep = "-"))
sogo_1901_2001$date <- as.Date(sogo_1901_2001$date)

# 変数名の英語化
sogo_1901_2001 <- sogo_1901_2001 %>% rename(prefec = "都道府県",   sogo_number = "決定件数",  sogo_payment_amount = "決定金額")

# 月・年データの削除
sogo_1901_2001 <- sogo_1901_2001 %>% select(-月, -年)

# 緊急小口資金と総合支援資金データの統合：2019.01-2020.01
koguchi_sogo_1901_2001 <- dplyr::full_join(koguchi_1901_2001,sogo_1901_2001, by = c("prefec", "date"))

##コロナ後の緊急小口資金と総合支援資金##

# データ読み込み
koguchi_sogo_2004_2008 <- read_excel("koguchi_sogo_2004_2008.xlsx")
## ※ 本集計は速報値としてとりまとめたものであり、件数、金額に変動が生じることがある。
## ※ 貸付の決定については、8月1日までに申請があったものについて8月5日時点で確認したもの。

# wide > long by tidyr::pivot_longer
koguchi_sogo_2004_2008 <- koguchi_sogo_2004_2008 %>%
  tidyr::pivot_longer(col = -prefec, names_to = "name", values_to = "number")

## "gather" version (old): koguchi_sogo_2004_2008 <- tidyr::gather(data = koguchi_sogo_2004_2008, key = "name", value = "number", -c("prefec"))

# 変数カテゴリ(category)の作成
koguchi_sogo_2004_2008 <-koguchi_sogo_2004_2008 %>% mutate(category = dplyr::case_when(
   stringr::str_detect(name, "koguchi_apply") ~ "koguchi_apply",
    stringr::str_detect(name, "koguchi_number") ~ "koguchi_number",
    stringr::str_detect(name, "koguchi_payment_amount") ~ "koguchi_payment_amount",
    stringr::str_detect(name, "sogo_apply") ~ "sogo_apply",
    stringr::str_detect(name, "sogo_number") ~ "sogo_number",
    stringr::str_detect(name, "sogo_payment_amount") ~ "sogo_payment_amount"
))

# 月次(date)の作成
koguchi_sogo_2004_2008 <-koguchi_sogo_2004_2008 %>% dplyr::mutate(date = dplyr::case_when(
   stringr::str_detect(name, "3/25～5/2") ~ "2020-04-01",
   stringr::str_detect(name, "5/3～5/30") ~ "2020-05-01",
   stringr::str_detect(name, "5/31～6/27") ~ "2020-06-01",
   stringr::str_detect(name, "6/28～8/1") ~ "2020-07-01",
   stringr::str_detect(name, "8/2～/15") ~ "2020-08-01"
))
## 提供されたデータの区切りがイレギュラーだが、大まかに4,5,6,7月分と8月半月分なので、このように区切る。8月分を使用する際には注意すること。

# dateデータ作成
koguchi_sogo_2004_2008$date <- as.Date(koguchi_sogo_2004_2008$date)

# numberデータ作成
koguchi_sogo_2004_2008$number <- as.numeric(koguchi_sogo_2004_2008$number)

# name削除
koguchi_sogo_2004_2008 <- koguchi_sogo_2004_2008 %>% select(-name)

# 合計>全国に変換
jukyo1901_2006 <- jukyo1901_2006 %>% dplyr::mutate(prefec = dplyr::case_when(
   stringr::str_detect(prefec, "合     計") ~ "全国",
   stringr::str_detect(prefec, "合計") ~ "全国",
   TRUE ~ prefec
))

koguchi_sogo_1901_2001 <- koguchi_sogo_1901_2001 %>% dplyr::mutate(prefec = dplyr::case_when(
   stringr::str_detect(prefec, "合     計") ~ "全国",
   stringr::str_detect(prefec, "合計") ~ "全国",
   TRUE ~ prefec
))

# 住居確保(全体）、緊急小口、総合支援(before COVID-19)１データの統合
df_merge <- dplyr::full_join(jukyo1901_2006, koguchi_sogo_1901_2001, by = c("prefec", "date"))

# wide > long by tidyr::pivot_longer
df_merge <- df_merge %>%
  tidyr::pivot_longer(col = -c(prefec,date), names_to = "category", values_to = "number")

# "gather" version (old): df_merge <- tidyr::gather(data = df_merge, key = "category", value = "number", -c("prefec", "date"))


# 合計>全国に変換
koguchi_sogo_2004_2008 <- koguchi_sogo_2004_2008 %>% dplyr::mutate(prefec = dplyr::case_when(
   stringr::str_detect(prefec, "合     計") ~ "全国",
   stringr::str_detect(prefec, "合計") ~ "全国",
   TRUE ~ prefec
))

# 緊急小口・総合支援（after corona)の結合
df_merge <- dplyr::bind_rows(df_merge, koguchi_sogo_2004_2008)

# categoryに基づいてname変数の作成
df_merge <- df_merge %>% dplyr::mutate(name = dplyr::case_when(
   stringr::str_detect(category, "koguchi") ~"koguchi",
   stringr::str_detect(category, "sogo") ~"sogo",
   stringr::str_detect(category, "jukyo") ~"jukyo"
))

# 人口データdf作成（全国グラフでは未使用）
population <- read_excel("prefec_pop_estimates2019.xlsx")

##平成30年10月1日現在

# 人口データ統合
df_merge <- dplyr::full_join(df_merge, population, by = "prefec")

# 8月データは除外（8/15までしかデータなし）
df_merge <- df_merge %>% filter(date != "2020-08-01")

# per capita dataの作成(全国データのグラフでは使わず）
df_merge <- df_merge %>% dplyr::mutate(per_pop = (number/population))

# raw data作成
raw_data <- df_merge %>%  select(-population, -per_pop)

raw_data <- raw_data %>% dplyr::mutate(data = "raw_data")

#per population dataの作成
per_pop <- df_merge %>% select(-number, -population)

per_pop <- per_pop %>% dplyr::mutate(data = "per_pop")

per_pop <- per_pop %>% rename("number" = "per_pop")

#raw dataとper pop dataの統合
df_merged <- dplyr::bind_rows(raw_data, per_pop)
```


```{r,include=FALSE}
## Generate "long" data frames for RMarkdown and R analysis

# Select necesssary data for raw-number df
df_num <- df_merge %>% select(prefec, date, category, number)

# Wide > Long data
df_long_num <- df_num %>% group_by(prefec,category,date) %>%
  mutate(id = dplyr::row_number()) %>% 
  tidyr::pivot_wider(names_from = category, values_from = number)
## "spread" version: tidyr::spread(key = category, value = number)

# Select necesssary data for per capita df
df_pop <- df_merge %>% select(prefec, date, category,per_pop)

# Wide > Long data
df_long_pop <- df_pop %>% group_by(prefec,category,date) %>%
  mutate(id = dplyr::row_number()) %>% 
  tidyr::pivot_wider(names_from = category, values_from = per_pop)
## "spread" version: tidyr::spread(key =  category, value = per_pop)
```


```{r, include=FALSE}
# rm(list = ls())
# データの読み込み
# フォルダ内のcsvファイル(被保護者調査の月例調査）をすべて読み込む
files = fs::dir_ls(glob = "*.csv")

combined_df = purrr::map_dfr(files, readr::read_csv)
```


```{r,include=FALSE}
##「被保護者調査」のデータ読み込み##

# 変数名の英語化
df <- combined_df %>% rename("city" = "統計表１　生活保護の被保護世帯数及び実人員",
                             "municipality" = "...2",
                             "households_total" = "...4" ,
                             "households_receive" = "...5",
                             "households_suspend" = "...6",
                             "persons_total" = "...7",
                             "persons_receive" = "...8",
                             "persons_suspend" = "...9",
                             "households_start" = "...10",
                             "households_end" = "...11" )

#municipalityと同じ列に全国を追加する
df <- df %>% mutate(municipality= dplyr::case_when(
  city == "全国" ~ "全国",
  TRUE ~ df$municipality
))

df <- df %>% select(-city, -"...3")

df <- subset(df, !(is.na(df$municipality)))

df[,2:9] <- lapply(df[,2:9], as.numeric)
```

```{r,include=FALSE}
##自治体コードの読み込みと統合##

region_code <- read_excel("region_code.xls")

region_code <- region_code　 %>% rename("municipality" =   "市区町村名\n（漢字）")

df <- dplyr::full_join(df, region_code, by = "municipality")

df <-df %>% rename("prefecture" = "都道府県名\n（漢字）")

df <- df %>% select(-"団体コード",-"都道府県名\n（カナ）", -"市区町村名\n（カナ）")

df <- df[, c(10,1,11,2,3,4,5,6,7,8,9)]
```

```{r,include=FALSE}
##「被保護者調査」の前処理##

for (i in 1:nrow(df)){
if (is.na(df[i,3])){
   df[i,3] <- df[i,2]
}else {
  df[i,3] <- df[i,3]
}}

df$prefecture <- stringr::str_replace(df$prefecture, "県", "")
df$prefecture <-stringr::str_replace(df$prefecture, "府", "")
df$prefecture <-stringr::str_replace(df$prefecture, "東京都", "東京")


df <- aggregate(df[c("households_total","households_receive","households_suspend","persons_total" ,"persons_receive","persons_suspend","households_start","households_end")], by=list(df$prefecture, df$year_month), FUN=sum)

df <- df %>% rename("prefecture"  = "Group.1",
                    "year_month" = "Group.2")

```

```{r,include=FALSE}
##都道府県人口の読み込みと統合##

population <- read_excel("prefec_pop_estimates2019.xlsx")

population$prefec <- stringr::str_replace(population$prefec, "県", "")
population$prefec <-stringr::str_replace(population$prefec, "府", "")
population$prefec <-stringr::str_replace(population$prefec, "東京都", "東京")

population$population  <- stringr::str_replace(population$population, ",", "")

population$population <- as.numeric(population$population)

population$population <- population$population

population <- population %>% rename("prefecture" = "prefec")

df <- dplyr::full_join(df, population, by = "prefecture")
```

```{r, eval=FALSE}
##「被保護者調査」の変数名の日本語化(shiny用のため使用せず)##
df <- df %>% rename("都道府県"  = "prefecture",
                    "年月" = "year_month",
                    "被保護世帯数_総数" = "households_total",
                    "被保護世帯数_現に保護を受けたもの" = "households_receive",
                    "被保護世帯数_保護停止中のもの"  = "households_suspend",
                    "被保護実人員_総数" = "persons_total",
                    "被保護実人員_現に保護を受けたもの" = "persons_receive",
                    "被保護実人員_保護停止中のもの" = "persons_suspend",
                    "保護開始世帯数" = "households_start",
                    "保護廃止世帯数" = "households_end"
                    )
```

```{r,include=FALSE}
## 「被保護者調査」の前処理 ##

#全国データの抽出
df_all　 <- df %>% filter(prefecture == "全国")

#都道府県データの抽出
df <- df %>% filter(prefecture != "全国")

#全国データの前月差データの作成
df_all <- df_all %>% mutate(diff_households_total = NA) 

for (i in 2:nrow(df_all)) {
  df_all$diff_households_total[i] <- df_all$households_total[i] - df_all$households_total[i-1]
}

df_all$diff_households_total[1] <- 0

df_all <- df_all %>% mutate(diff_persons_total = NA) 

for (i in 2:nrow(df_all)) {
  df_all$diff_persons_total[i] <- df_all$persons_total[i] - df_all$persons_total[i-1]
}

df_all$diff_persons_total[1] <- 0

df_all <- df_all %>% mutate(per_mille_diff_households_total = df_all$diff_households_total/df_all$population)

df_all <- df_all%>% mutate(per_mille_diff_persons_total = df_all$diff_persons_total/df_all$population)


df <- df %>% mutate(per_mille_households_total = df$households_total/df$population)

df <- df %>% mutate(per_mille_persons_total = df$persons_total/df$population)

df <- df %>% mutate(per_mille_households_start = df$households_start/df$population)

df <- df %>% mutate(per_mille_households_end = df$households_end/df$population)

df <- df[order(df$prefecture, decreasing=F),]

df <- df %>% mutate(diff_households_total = NA) 

for (i in 2:nrow(df)) {
  df$diff_households_total[i] <- df$households_total[i] - df$households_total[i-1]
}

df[df$year_month=="2019-01-01", "diff_households_total"] <- 0

df <- df %>% mutate(per_mille_diff_households_total = df$diff_households_total/df$population)

df <- df %>% mutate(diff_persons_total = NA) 

for (i in 2:nrow(df)) {
  df$diff_persons_total[i] <- df$persons_total[i] - df$persons_total[i-1]
}

df[df$year_month=="2019-01-01", "diff_persons_total"] <- 0

df <- df %>% mutate(per_mille_diff_persons_total = df$diff_persons_total/df$population)
```


```{r,include=FALSE}
#Wide > Long, using "number" ()
df_all_long <- df_all %>%
  tidyr::pivot_longer(col = -c("prefecture","year_month" ,"population"), names_to = "category", values_to = "number")

## "gather" version: df_all_long <- tidyr::gather(data = df_all, key = "category", value = "number",-c("prefecture","year_month" ,"population"))

df_all_long <- df_all_long %>% mutate(per_pop = df_all_long$number/df_all_long$population)

## Old, Change unit :df_all_long$number <- df_all_long$number/10000 

df_all_long <- df_all_long[order(df_all_long$category, decreasing=F),]

df_all_long <- df_all_long %>% mutate(diff = NA) 

for (i in 2:nrow(df_all_long)) {
  df_all_long$diff[i] <- df_all_long$number[i] - df_all_long$number[i-1]
}

df_all_long[df_all_long$year_month=="2019-01-01", "diff"] <- 0
```

```{r,include=FALSE}
# df_long <- tidyr::gather(data = df, key = "category", value = "number",-c("prefecture","year_month" ,"population"))

df_long <- df %>%
  tidyr::pivot_longer(col = -c("prefecture","year_month" ,"population"), names_to = "category", values_to = "number")

df_long <- df_long %>% mutate(per_pop = df_long$number/df_long$population)


df_long <- df_long[order(df_long$prefecture, decreasing=F),]

df_long <- df_long %>% mutate(diff = NA) 

df_long <- df_long[order(df_long$category, decreasing=F),]

for (i in 2:nrow(df_long)) {
  df_long$diff[i] <- df_long$number[i] - df_long$number[i-1]
}

df_long[df_long$year_month=="2019-01-01", "diff"] <- 0

#df_wide <- df_long %>% tidyr::spread(data = df_long, key = "category", value = "per_mille",-c("prefecture","year_month" ,"population", "number"))
```


```{r,include=FALSE}
# df_long <- tidyr::gather(data = df, key = "category", value = "number",-c("prefecture","year_month" ,"population"))

df_long <- df %>%
  tidyr::pivot_longer(col = -c("prefecture","year_month" ,"population"), names_to = "category", values_to = "number")

df_long <- df_long %>% mutate(per_pop = df_long$number/df_long$population)


df_long <- df_long[order(df_long$prefecture, decreasing=F),]

df_long <- df_long %>% mutate(diff = NA) 

df_long <- df_long[order(df_long$category, decreasing=F),]

for (i in 2:nrow(df_long)) {
  df_long$diff[i] <- df_long$number[i] - df_long$number[i-1]
}

df_long[df_long$year_month=="2019-01-01", "diff"] <- 0

#df_wide <- df_long %>% tidyr::spread(data = df_long, key = "category", value = "per_mille",-c("prefecture","year_month" ,"population", "number"))
```


# 全国での集計値

## 生活保護世帯数
```{r}
seikatsu <- df_all_long

seikatsu　 <- seikatsu %>% filter(category == "households_total")

seikatsu　 <- seikatsu %>% rename("households_total"= number)

seikatsu$households_total <- seikatsu$households_total/10000

g_seiho_households <- seikatsu %>% ggplot(aes(x = year_month, y = households_total)) +
   　 geom_line(stat = "identity",  colour = "#1177CC") +
      geom_point(stat = "identity", colour = "#1177CC") +
      theme_minimal(base_family = font) +
 　　 scale_x_date(breaks = "2 month", date_labels = "%Y-%m") +
   　 theme(axis.text.x = element_text(angle = 30, hjust = 1)) +
   　 ylab("被保護世帯（単位：1万世帯）")  +
      xlab("年月") +
      scale_y_continuous(limits = c(155, 165),oob = rescale_none)

ggplotly(g_seiho_households)
```

```{r, include=FALSE}
# pngで出力
ggsave(file = "seiho_households.png", plot = g_seiho_households)

# グラフ統合用
g_seiho_households <- g_seiho_households + ggtitle("(a)世帯数") +
   theme(axis.text.x = element_text(angle = 30, hjust = 1)) 
```


## 生活保護世帯数の前月差
```{r}
seikatsu <-  df_all_long

seikatsu　 <- seikatsu %>% filter(category == "households_total")

seikatsu　 <- seikatsu %>% rename("diff_households_total"= diff)

g_seiho_households_diff <- seikatsu %>% ggplot(aes(x=year_month, y=diff_households_total)) +
   　 geom_line(stat = "identity",  colour = "#1177CC") +
      geom_point(stat = "identity", colour = "#1177CC") +
      theme_minimal(base_family = font) +
 　　 scale_x_date(breaks = "2 month", date_labels = "%Y-%m") +
   　 ylab("被保護世帯（単位：1万世帯）")  +
      xlab("年月") +
      geom_hline(yintercept = 0, color = "black", linetype = "dashed") +
   　 theme(axis.text.x = element_text(angle= 0, hjust = 1))
    
ggplotly(g_seiho_households_diff)
```

```{r, include=FALSE}
# pngで出力
ggsave(file = "seiho_households_diff.png", plot = g_seiho_households_diff)
```


## 生活保護人員数
```{r}
seikatsu <-  df_all_long

seikatsu　 <- seikatsu %>% filter(category == "persons_total")

seikatsu　 <- seikatsu %>% rename("persons_total"= number)

seikatsu$persons_total <- seikatsu$persons_total/10000

g_seiho_people <- seikatsu %>% ggplot(aes(x=year_month, y=persons_total)) +
   　geom_line(stat = "identity",  colour = "#1177CC") +
      geom_point(stat = "identity", colour = "#1177CC") +
      theme_minimal(base_family = font) +
 　　 scale_x_date(breaks = "2 month", date_labels = "%Y-%m") +
   　 theme(axis.text.x = element_text(angle = 30, hjust = 1))+
   　 ylab("被保護世帯（単位：1万人）")  +
      xlab("年月") +
      scale_y_continuous(limits = c(200,  210),oob = rescale_none)
    
ggplotly(g_seiho_people)
```

```{r, include=FALSE}
# pngで出力
ggsave(file = "seiho_people.png", plot = g_seiho_people)

# グラフ統合用
g_seiho_people <- g_seiho_people + ggtitle("(b)人員数") +
     　 theme(axis.text.x = element_text(angle = 30, hjust = 1))
```


## 生活保護人員数の前月差
```{r}
seikatsu <-  df_all_long

seikatsu　 <- seikatsu %>% filter(category == "persons_total")

seikatsu　 <- seikatsu %>% rename("diff_persons_total"= diff)

g_seiho_people_diff <- seikatsu %>% ggplot(aes(x=year_month, y=diff_persons_total)) +
   　geom_line(stat = "identity",  colour = "#1177CC") +
      geom_point(stat = "identity", colour = "#1177CC") +
      theme_minimal (base_family = font) +
 　　 scale_x_date(breaks = "2 month", date_labels = "%Y-%m") +
   　 theme(axis.text.x = element_text(angle = 30, hjust = 1))+
   　 ylab("被保護世帯（単位：1万人）")  +
      xlab("年月") +
      geom_hline(yintercept = 0, color = "black", linetype = "dashed") +
      geom_vline(aes(xintercept = as.Date("2020-01-01")))
    
ggplotly(g_seiho_people_diff)
```

```{r, include=FALSE}
#png出力
ggsave(file = "seiho_people_diff.png", plot = g_seiho_people_diff)
```


```{r, include=FALSE}
## 生活保護世帯数と人員数のグラフ統合とpng保存##
g_seiho_merge <- g_seiho_households + g_seiho_people +
  plot_annotation(
    title = "図１：生活保護の被保護世帯数・人員数",
    caption = "出典：「被保護者調査」（月次調査）の速報値　https://www.mhlw.go.jp/toukei/list/74-16b.html#link01",
    theme = theme(plot.title = element_text(size = 20)))
  
# png出力
ggsave(file = "seiho_household_people.png", plot = g_seiho_merge, width = 9, height = 4.5) 
```
 

## 住居確保給付金
### 住居確保給付金の申請件数
```{r}
jukyo1901_2006 <- df_long_num %>% select(prefec, date, jukyo_apply)

jukyo1901_2006 <-na.omit(jukyo1901_2006)

jukyo1901_2006　 <- jukyo1901_2006　 %>% filter(prefec == "全国")

jukyo1901_2006 <- jukyo1901_2006 %>% rename("year_month" = date)

g_jukyo_apply <- jukyo1901_2006 %>% ggplot(aes(x = year_month, y = jukyo_apply)) +
 　geom_line(stat = "identity",  colour = "#1177CC") +
   geom_point(stat = "identity", colour = "#1177CC") +
   theme_minimal(base_family = font) +
   scale_x_date(breaks = "2 month", date_labels = "%Y-%m") +
   theme(axis.text.x = element_text(angle = 30, hjust = 1))+
   xlab("年月") +
   ylab("申請件数")+
   labs(colour="prefecture")+
   scale_y_continuous(limits = c(0, 45000),oob = rescale_none) +
   theme(legend.position="none")

ggplotly(g_jukyo_apply)

# グラフ統合用
g_jukyo_apply <- g_jukyo_apply + ggtitle("(a)申請件数") +
     theme(axis.text.x = element_text(angle = 30, hjust = 1))
```


### 住居確保給付金の決定件数
```{r}
jukyo1901_2006 <- df_long_num %>% select(prefec, date, jukyo_number)

jukyo1901_2006 <-na.omit(jukyo1901_2006)

jukyo1901_2006　 <- jukyo1901_2006　 %>% filter(prefec == "全国")

jukyo1901_2006 <- jukyo1901_2006 %>% rename("year_month" = date, "prefecture" = prefec)

g_jukyo_number <- jukyo1901_2006 %>% ggplot(aes(x = year_month, y = jukyo_number)) +
 　geom_line(stat = "identity",  colour = "#1177CC") +
   geom_point(stat = "identity", colour = "#1177CC") +
   theme_minimal(base_family = font) +
   scale_x_date(breaks = "2 month", date_labels = "%Y-%m") +
   theme(axis.text.x = element_text(angle = 30, hjust=1))+
   xlab("年月") +
   ylab("決定件数")+
   labs(colour="prefecture")+
   scale_y_continuous(limits = c(0, 45000),oob = rescale_none) +
   theme(legend.position="none")

ggplotly(g_jukyo_number)

# グラフ統合用
g_jukyo_number <- g_jukyo_number + ggtitle("(b)決定件数") +
     theme(axis.text.x = element_text(angle = 30, hjust=1))
```


```{r, include=FALSE}
## 住居確保給付金の新政権すと決定件数のグラフ統合とpng保存##
g_jukyo_merge <- g_jukyo_apply + g_jukyo_number +
  plot_annotation(
    title = "図２ 住居確保給付金の申請件数・決定件数",
    caption = "注：2019年4月から2020年3月については、統計が欠損している。 出典：厚生労働省提供資料",
    theme = theme(plot.title = element_text(size = 20)))

# png出力
ggsave(file = "jukyo_apply_number.png", plot = g_jukyo_merge, width = 9, height = 4.5) 
```
 
 
### 住居確保給付金の支給済額
```{r}
jukyo1901_2006 <- df_long_num %>% select(prefec, date, jukyo_payment_amount)

jukyo1901_2006 <-na.omit(jukyo1901_2006)

jukyo1901_2006　 <- jukyo1901_2006　 %>% filter(prefec == "全国")

jukyo1901_2006$jukyo_payment_amount <- jukyo1901_2006$jukyo_payment_amount/100000

jukyo1901_2006 <- jukyo1901_2006 %>% rename("year_month" = date)

g_jukyo_amounts <- jukyo1901_2006 %>% ggplot(aes(x = year_month, y = jukyo_payment_amount)) +
 　geom_line(stat = "identity",  colour = "#1177CC") +
   geom_point(stat = "identity", colour = "#1177CC") +
   theme_minimal(base_family = font) +
   scale_x_date(breaks = "2 month", date_labels = "%Y-%m") +
   theme(axis.text.x = element_text(angle = 30, hjust=1))+
   xlab("年月") +
   ylab("支給済額（単位：億円）") +
   theme(legend.position="none") 

ggplotly(g_jukyo_amounts)

# 出力用グラフ
g_jukyo_amounts <- g_jukyo_amounts +  labs(title = "図３ 住居確保給付金の支給済額（単位：億円）",
      caption = "注：2019年4月から2020年3月については統計が欠損している。出典：厚生労働省提供資料")

# png出力
ggsave(file = "jukyo_amounts.png", plot = g_jukyo_amounts, width = 5, height = 4) 

```


## 緊急小口資金・総合支援資金

### 緊急小口資金の申請件数
```{r}
koguchi_1901_2008 <- df_long_num %>% select(prefec, date,koguchi_apply)

koguchi_1901_2008 <- na.omit(koguchi_1901_2008)
   
koguchi_1901_2008 <- koguchi_1901_2008  %>% filter(prefec == "全国")

koguchi_1901_2008 <- koguchi_1901_2008　%>% rename("year_month" = date)

g_koguchi_apply <- koguchi_1901_2008 %>% ggplot(aes(x = year_month, y = koguchi_apply)) +
 　geom_line(stat = "identity",  colour = "#1177CC") +
   geom_point(stat = "identity", colour = "#1177CC") +
   theme_minimal (base_family = font) +
   scale_x_date(breaks = "2 month", date_labels = "%Y-%m",
                limit=c(as.Date("2019-01-01"),as.Date("2020-08-01"))) +
   scale_y_continuous(limits = c(0, 200000),oob = rescale_none) +
   theme(axis.text.x = element_text(angle = 30, hjust=1))+
   xlab("年月") +
   ylab("申請件数")+
   theme(legend.position="none") 

ggplotly(g_koguchi_apply)
g_koguchi_apply <- g_koguchi_apply + ggtitle("(a)緊急小口資金の申請件数") +
      theme(axis.text.x = element_text(angle=30, hjust=1))

```

### 緊急小口資金の決定件数
```{r}
koguchi_1901_2008 <- df_long_num %>% select(prefec, date,koguchi_number)

koguchi_1901_2008 <- na.omit(koguchi_1901_2008)
   
koguchi_1901_2008 <- koguchi_1901_2008  %>% filter(prefec == "全国")

koguchi_1901_2008 <- koguchi_1901_2008　%>% rename("year_month" = date)

g_koguchi_number <- koguchi_1901_2008 %>% ggplot(aes(x = year_month, y =　koguchi_number)) +
 　geom_line(stat = "identity",  colour = "#1177CC") +
   geom_point(stat = "identity", colour = "#1177CC") +
   theme_minimal (base_family = font) +
   scale_x_date(breaks = "2 month", date_labels = "%Y-%m") +
   scale_y_continuous(limits = c(0, 200000),oob = rescale_none) +
   theme(axis.text.x = element_text(angle = 30, hjust=1))+
   xlab("年月") +
   ylab("決定件数")+
   theme(legend.position="none")

ggplotly(g_koguchi_number)

g_koguchi_number <- g_koguchi_number + ggtitle("(b)緊急小口資金の決定件数") +
      theme(axis.text.x = element_text(angle=30, hjust=1))

```

### 総合支援資金の申請件数
```{r}
sogo_1901_2001 <- df_long_num %>% select(prefec, date,sogo_apply)

sogo_1901_2001 <- na.omit(sogo_1901_2001)
   
sogo_1901_2001 <- sogo_1901_2001 　 %>% filter(prefec == "全国")

sogo_1901_2001  <- sogo_1901_2001 　%>% rename("year_month" = date)

g_sogo_apply <- sogo_1901_2001 %>% ggplot(aes(x = year_month, y =　sogo_apply)) +
 　geom_line(stat = "identity",  colour = "#1177CC") +
   geom_point(stat = "identity", colour = "#1177CC") +
   theme_minimal (base_family = font) +
   scale_x_date(breaks = "2 month", date_labels = "%Y-%m",
                limit=c(as.Date("2019-01-01"),as.Date("2020-08-01"))) +
   scale_y_continuous(limits = c(0, 200000),oob = rescale_none) +
   theme(axis.text.x = element_text(angle = 30, hjust = 1))+
   xlab("年月") +
   ylab("申請件数")+
   theme(legend.position="none")

ggplotly(g_sogo_apply)

# 統合用
g_sogo_apply <- g_sogo_apply + ggtitle("(c)総合支援資金の申請件数")　+
     theme(axis.text.x = element_text(angle=30, hjust=1))
```

### 総合支援資金の決定件数
```{r}
sogo_1901_2001 <- df_long_num %>% select(prefec, date,sogo_number)

sogo_1901_2001 <- na.omit(sogo_1901_2001)
   
sogo_1901_2001 <- sogo_1901_2001 　 %>% filter(prefec == "全国")

sogo_1901_2001  <- sogo_1901_2001 　%>% rename("year_month" = date)

g_sogo_number  <- sogo_1901_2001 %>% ggplot(aes(x = year_month, y =sogo_number)) +
 　geom_line(stat = "identity",  colour = "#1177CC") +
   geom_point(stat = "identity", colour = "#1177CC") +
   theme_minimal (base_family = font) +
   scale_x_date(breaks = "2 month", date_labels = "%Y-%m") +
   scale_y_continuous(limits = c(0, 200000),oob = rescale_none) +
   theme(axis.text.x = element_text(angle=30, hjust=1))+
   xlab("年月") +
   ylab("決定件数")+
   theme(legend.position="none")

ggplotly(g_sogo_number)

g_sogo_number <- g_sogo_number  + ggtitle("(d)総合支援資金の決定件数")
```


```{r, include=FALSE}
## 緊急小口と総合支援のグラフ統合とpng保存##

# 件数
g_koguchi_sogo_apply_number <- (g_koguchi_apply + g_koguchi_number) / ( g_sogo_apply + g_sogo_number) +
  plot_annotation(
    title = "図４ 緊急小口資金・総合支援資金の申請件数と決定件数",
    caption = "注：緊急小口資金・総合支援資金ともに、2019年1月から2020年3月までの申請件数および2020年2月、3月の決定件数については、統計が欠損している。\n また、2020年４月～7月は、実際には3月25日～5月2日、5月3日～5月30日、5月31日～6月27日、6月28日～8月1日の集計値である。\n 出典：厚生労働省提供資料",
    theme = theme(plot.title = element_text(size = 20)))

# png出力
ggsave(file = "koguchi_sogo_apply_number.png", plot = g_koguchi_sogo_apply_number, width = 9, height = 6) 
```


### 緊急小口資金の決定金額
```{r}
koguchi_1901_2008 <- df_long_num%>% select(prefec, date,koguchi_payment_amount)

koguchi_1901_2008 <- na.omit(koguchi_1901_2008)

koguchi_1901_2008 　 <-koguchi_1901_2008 　 %>% filter(prefec == "全国")

koguchi_1901_2008$koguchi_payment_amount <- koguchi_1901_2008$koguchi_payment_amount/100000

koguchi_1901_2008 <- koguchi_1901_2008　%>% rename("year_month" = date)

g_koguchi_amounts <- koguchi_1901_2008 %>% ggplot(aes(x = year_month, y = koguchi_payment_amount)) +
 　geom_line(stat = "identity",  colour = "#1177CC") +
   geom_point(stat = "identity", colour = "#1177CC") +
   theme_minimal (base_family = font) +
   scale_x_date(breaks = "2 month", date_labels = "%Y-%m") +
   theme(axis.text.x = element_text(angle = 30, hjust=1))+
   xlab("年月") +
   ylab("決定金額（億円）")+
   theme(legend.position="none")

ggplotly(g_koguchi_amounts)

g_koguchi_amounts <- g_koguchi_amounts + ggtitle("(a)緊急小口資金の決定金額") +
      theme(axis.text.x = element_text(angle=30, hjust=1))

```


### 総合支援資金の決定金額
```{r}
sogo_1901_2001 <- df_long_num %>% select(prefec, date,sogo_payment_amount)

sogo_1901_2001 <- na.omit(sogo_1901_2001)

sogo_1901_2001 　 <-sogo_1901_2001 　 %>% filter(prefec == "全国")

sogo_1901_2001$sogo_payment_amount <- sogo_1901_2001$sogo_payment_amount/100000

sogo_1901_2001  <- sogo_1901_2001 　%>% rename("year_month" = date)

g_sogo_amounts <- sogo_1901_2001 %>% ggplot(aes(x = year_month, y = sogo_payment_amount)) +
 　geom_line(stat = "identity",  colour = "#1177CC") +
   geom_point(stat = "identity", colour = "#1177CC") +
   theme_minimal (base_family = font) +
   scale_x_date(breaks = "2 month", date_labels = "%Y-%m") +
   theme(axis.text.x = element_text(angle=30, hjust=1))+
   xlab("年月") +
   ylab("決定金額（億円）")+
   theme(legend.position="none")

ggplotly(g_sogo_amounts)

g_sogo_amounts <- g_sogo_amounts + ggtitle("(b)総合支援資金の決定金額") +
      theme(axis.text.x = element_text(angle=30, hjust=1))
```


```{r, include=FALSE}
## 緊急小口と総合支援のグラフ統合とpng保存 ##

# 金額
g_koguchi_sogo_amounts <- g_koguchi_amounts + g_sogo_amounts +
  plot_annotation(
    title = "図５ 緊急小口資金・総合支援資金の決定金額（億円）",
    caption = "注：緊急小口資金・総合支援資金ともに、2020年2月、3月の決定金額については、統計が欠損している。\n また、2020年４月～7月は、実際には3月25日～5月2日、5月3日～5月30日、5月31日～6月27日、6月28日～8月1日の集計値である。\n 出典：厚生労働省提供資料",
    theme = theme(plot.title = element_text(size = 20)))

g_koguchi_sogo_amounts

# png出力
ggsave(file = "koguchi_sogo_amounts.png", plot = g_koguchi_sogo_amounts, width = 9, height = 4.5) 
```



